// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryRegisteredBtcDepositAddressesRequest struct {
}

func (m *QueryRegisteredBtcDepositAddressesRequest) Reset() {
	*m = QueryRegisteredBtcDepositAddressesRequest{}
}
func (m *QueryRegisteredBtcDepositAddressesRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryRegisteredBtcDepositAddressesRequest) ProtoMessage() {}
func (*QueryRegisteredBtcDepositAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{2}
}
func (m *QueryRegisteredBtcDepositAddressesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredBtcDepositAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredBtcDepositAddressesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredBtcDepositAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressesRequest.Merge(m, src)
}
func (m *QueryRegisteredBtcDepositAddressesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredBtcDepositAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredBtcDepositAddressesRequest proto.InternalMessageInfo

type QueryRegisteredBtcDepositAddressesResponse struct {
	Addresses []MsgRegisterBtcDepositAddress `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses"`
}

func (m *QueryRegisteredBtcDepositAddressesResponse) Reset() {
	*m = QueryRegisteredBtcDepositAddressesResponse{}
}
func (m *QueryRegisteredBtcDepositAddressesResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryRegisteredBtcDepositAddressesResponse) ProtoMessage() {}
func (*QueryRegisteredBtcDepositAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{3}
}
func (m *QueryRegisteredBtcDepositAddressesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredBtcDepositAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredBtcDepositAddressesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredBtcDepositAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressesResponse.Merge(m, src)
}
func (m *QueryRegisteredBtcDepositAddressesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredBtcDepositAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredBtcDepositAddressesResponse proto.InternalMessageInfo

func (m *QueryRegisteredBtcDepositAddressesResponse) GetAddresses() []MsgRegisterBtcDepositAddress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type QueryRegisteredReserveScriptsRequest struct {
}

func (m *QueryRegisteredReserveScriptsRequest) Reset()         { *m = QueryRegisteredReserveScriptsRequest{} }
func (m *QueryRegisteredReserveScriptsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegisteredReserveScriptsRequest) ProtoMessage()    {}
func (*QueryRegisteredReserveScriptsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{4}
}
func (m *QueryRegisteredReserveScriptsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredReserveScriptsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredReserveScriptsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredReserveScriptsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredReserveScriptsRequest.Merge(m, src)
}
func (m *QueryRegisteredReserveScriptsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredReserveScriptsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredReserveScriptsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredReserveScriptsRequest proto.InternalMessageInfo

type QueryRegisteredReserveScriptsResponse struct {
	Scripts []MsgRegisterReserveAddress `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts"`
}

func (m *QueryRegisteredReserveScriptsResponse) Reset()         { *m = QueryRegisteredReserveScriptsResponse{} }
func (m *QueryRegisteredReserveScriptsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegisteredReserveScriptsResponse) ProtoMessage()    {}
func (*QueryRegisteredReserveScriptsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{5}
}
func (m *QueryRegisteredReserveScriptsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredReserveScriptsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredReserveScriptsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredReserveScriptsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredReserveScriptsResponse.Merge(m, src)
}
func (m *QueryRegisteredReserveScriptsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredReserveScriptsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredReserveScriptsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredReserveScriptsResponse proto.InternalMessageInfo

func (m *QueryRegisteredReserveScriptsResponse) GetScripts() []MsgRegisterReserveAddress {
	if m != nil {
		return m.Scripts
	}
	return nil
}

type QueryRegisteredBtcDepositAddressRequest struct {
	DepositAddress string `protobuf:"bytes,1,opt,name=depositAddress,proto3" json:"depositAddress,omitempty"`
}

func (m *QueryRegisteredBtcDepositAddressRequest) Reset() {
	*m = QueryRegisteredBtcDepositAddressRequest{}
}
func (m *QueryRegisteredBtcDepositAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegisteredBtcDepositAddressRequest) ProtoMessage()    {}
func (*QueryRegisteredBtcDepositAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{6}
}
func (m *QueryRegisteredBtcDepositAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredBtcDepositAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredBtcDepositAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredBtcDepositAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressRequest.Merge(m, src)
}
func (m *QueryRegisteredBtcDepositAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredBtcDepositAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredBtcDepositAddressRequest proto.InternalMessageInfo

func (m *QueryRegisteredBtcDepositAddressRequest) GetDepositAddress() string {
	if m != nil {
		return m.DepositAddress
	}
	return ""
}

type QueryRegisteredBtcDepositAddressResponse struct {
	DepositAddress         string `protobuf:"bytes,1,opt,name=depositAddress,proto3" json:"depositAddress,omitempty"`
	TwilightDepositAddress string `protobuf:"bytes,2,opt,name=twilightDepositAddress,proto3" json:"twilightDepositAddress,omitempty"`
}

func (m *QueryRegisteredBtcDepositAddressResponse) Reset() {
	*m = QueryRegisteredBtcDepositAddressResponse{}
}
func (m *QueryRegisteredBtcDepositAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegisteredBtcDepositAddressResponse) ProtoMessage()    {}
func (*QueryRegisteredBtcDepositAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{7}
}
func (m *QueryRegisteredBtcDepositAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredBtcDepositAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredBtcDepositAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredBtcDepositAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressResponse.Merge(m, src)
}
func (m *QueryRegisteredBtcDepositAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredBtcDepositAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredBtcDepositAddressResponse proto.InternalMessageInfo

func (m *QueryRegisteredBtcDepositAddressResponse) GetDepositAddress() string {
	if m != nil {
		return m.DepositAddress
	}
	return ""
}

func (m *QueryRegisteredBtcDepositAddressResponse) GetTwilightDepositAddress() string {
	if m != nil {
		return m.TwilightDepositAddress
	}
	return ""
}

type QueryRegisteredBtcDepositAddressByTwilightAddressRequest struct {
	TwilightDepositAddress string `protobuf:"bytes,1,opt,name=twilightDepositAddress,proto3" json:"twilightDepositAddress,omitempty"`
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) Reset() {
	*m = QueryRegisteredBtcDepositAddressByTwilightAddressRequest{}
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryRegisteredBtcDepositAddressByTwilightAddressRequest) ProtoMessage() {}
func (*QueryRegisteredBtcDepositAddressByTwilightAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{8}
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressRequest.Merge(m, src)
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressRequest proto.InternalMessageInfo

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) GetTwilightDepositAddress() string {
	if m != nil {
		return m.TwilightDepositAddress
	}
	return ""
}

type QueryRegisteredBtcDepositAddressByTwilightAddressResponse struct {
	DepositAddress         string `protobuf:"bytes,1,opt,name=depositAddress,proto3" json:"depositAddress,omitempty"`
	TwilightDepositAddress string `protobuf:"bytes,2,opt,name=twilightDepositAddress,proto3" json:"twilightDepositAddress,omitempty"`
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) Reset() {
	*m = QueryRegisteredBtcDepositAddressByTwilightAddressResponse{}
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryRegisteredBtcDepositAddressByTwilightAddressResponse) ProtoMessage() {}
func (*QueryRegisteredBtcDepositAddressByTwilightAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09fd90c905cb448b, []int{9}
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressResponse.Merge(m, src)
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegisteredBtcDepositAddressByTwilightAddressResponse proto.InternalMessageInfo

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) GetDepositAddress() string {
	if m != nil {
		return m.DepositAddress
	}
	return ""
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) GetTwilightDepositAddress() string {
	if m != nil {
		return m.TwilightDepositAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "twilightproject.nyks.bridge.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "twilightproject.nyks.bridge.QueryParamsResponse")
	proto.RegisterType((*QueryRegisteredBtcDepositAddressesRequest)(nil), "twilightproject.nyks.bridge.QueryRegisteredBtcDepositAddressesRequest")
	proto.RegisterType((*QueryRegisteredBtcDepositAddressesResponse)(nil), "twilightproject.nyks.bridge.QueryRegisteredBtcDepositAddressesResponse")
	proto.RegisterType((*QueryRegisteredReserveScriptsRequest)(nil), "twilightproject.nyks.bridge.QueryRegisteredReserveScriptsRequest")
	proto.RegisterType((*QueryRegisteredReserveScriptsResponse)(nil), "twilightproject.nyks.bridge.QueryRegisteredReserveScriptsResponse")
	proto.RegisterType((*QueryRegisteredBtcDepositAddressRequest)(nil), "twilightproject.nyks.bridge.QueryRegisteredBtcDepositAddressRequest")
	proto.RegisterType((*QueryRegisteredBtcDepositAddressResponse)(nil), "twilightproject.nyks.bridge.QueryRegisteredBtcDepositAddressResponse")
	proto.RegisterType((*QueryRegisteredBtcDepositAddressByTwilightAddressRequest)(nil), "twilightproject.nyks.bridge.QueryRegisteredBtcDepositAddressByTwilightAddressRequest")
	proto.RegisterType((*QueryRegisteredBtcDepositAddressByTwilightAddressResponse)(nil), "twilightproject.nyks.bridge.QueryRegisteredBtcDepositAddressByTwilightAddressResponse")
}

func init() { proto.RegisterFile("bridge/query.proto", fileDescriptor_09fd90c905cb448b) }

var fileDescriptor_09fd90c905cb448b = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xc1, 0x6b, 0xd4, 0x4e,
	0x18, 0xdd, 0xd9, 0xdf, 0xcf, 0x4a, 0xa7, 0xa0, 0x30, 0x2d, 0xb2, 0xa4, 0x1a, 0x4b, 0xac, 0xb5,
	0xd6, 0x9a, 0xb1, 0x15, 0x4a, 0xeb, 0x41, 0xda, 0xa5, 0x56, 0x3c, 0x14, 0xed, 0x6a, 0x8b, 0x08,
	0x12, 0x92, 0xec, 0x90, 0xc6, 0xb6, 0x99, 0x74, 0x66, 0xb6, 0x76, 0x91, 0x22, 0x7a, 0xd4, 0x8b,
	0xe0, 0x49, 0xfc, 0x87, 0x7a, 0x5c, 0xf0, 0x22, 0x08, 0x22, 0xbb, 0xfe, 0x11, 0x1e, 0x65, 0x27,
	0x93, 0x2d, 0xd9, 0x76, 0xb3, 0xa9, 0x11, 0x6f, 0xcb, 0x37, 0xdf, 0x7b, 0xf3, 0xde, 0x37, 0xfb,
	0x3d, 0x02, 0x91, 0xc3, 0xfc, 0xaa, 0x47, 0xf0, 0x6e, 0x8d, 0xb0, 0xba, 0x19, 0x32, 0x2a, 0x28,
	0x1a, 0x15, 0x2f, 0xfd, 0x6d, 0xdf, 0xdb, 0x14, 0x21, 0xa3, 0x2f, 0x88, 0x2b, 0xcc, 0xa0, 0xbe,
	0xc5, 0xcd, 0xa8, 0x51, 0x1b, 0xf1, 0xa8, 0x47, 0x65, 0x1f, 0x6e, 0xff, 0x8a, 0x20, 0xda, 0x45,
	0x8f, 0x52, 0x6f, 0x9b, 0x60, 0x3b, 0xf4, 0xb1, 0x1d, 0x04, 0x54, 0xd8, 0xc2, 0xa7, 0x01, 0x57,
	0xa7, 0x53, 0x2e, 0xe5, 0x3b, 0x94, 0x63, 0xc7, 0xe6, 0xea, 0x26, 0xbc, 0x37, 0xe3, 0x10, 0x61,
	0xcf, 0xe0, 0xd0, 0xf6, 0xfc, 0x40, 0x36, 0xab, 0xde, 0xf3, 0x4a, 0x90, 0xd8, 0x57, 0x85, 0x61,
	0x55, 0x08, 0x6d, 0x66, 0xef, 0x28, 0x46, 0x63, 0x04, 0xa2, 0xb5, 0x36, 0xcf, 0x23, 0x59, 0xac,
	0x90, 0xdd, 0x1a, 0xe1, 0xc2, 0x78, 0x0a, 0x87, 0x13, 0x55, 0x1e, 0xd2, 0x80, 0x13, 0xb4, 0x04,
	0x07, 0x22, 0x70, 0x09, 0x8c, 0x81, 0xc9, 0xa1, 0xd9, 0x2b, 0x66, 0x8a, 0x41, 0x33, 0x02, 0x97,
	0xff, 0x3f, 0xfc, 0x7e, 0xb9, 0x50, 0x51, 0x40, 0xe3, 0x06, 0xbc, 0x2e, 0x99, 0x2b, 0xc4, 0xf3,
	0xb9, 0x20, 0x8c, 0x54, 0xcb, 0xc2, 0x5d, 0x26, 0x21, 0xe5, 0xbe, 0x58, 0xaa, 0x56, 0x19, 0xe1,
	0x9c, 0x74, 0x64, 0xbc, 0x07, 0x70, 0x2a, 0x4b, 0xb7, 0x92, 0xf7, 0x1c, 0x0e, 0xda, 0x71, 0xb1,
	0x04, 0xc6, 0xfe, 0x9b, 0x1c, 0x9a, 0x5d, 0x48, 0x55, 0xb8, 0xca, 0xbd, 0x98, 0xf9, 0x18, 0xaf,
	0xd2, 0x7d, 0xc4, 0x68, 0x4c, 0xc0, 0xf1, 0x2e, 0x31, 0x15, 0xc2, 0x09, 0xdb, 0x23, 0x8f, 0x5d,
	0xe6, 0x87, 0xa2, 0xa3, 0xfa, 0x35, 0xbc, 0xda, 0xa7, 0x4f, 0xe9, 0xdd, 0x80, 0x67, 0x79, 0x54,
	0x52, 0x6a, 0xe7, 0xb2, 0xaa, 0x55, 0x84, 0x49, 0xa9, 0x31, 0x99, 0xb1, 0x06, 0xaf, 0xf5, 0x9b,
	0x9a, 0xd2, 0x8a, 0x26, 0xe0, 0xb9, 0x6a, 0xe2, 0x40, 0xbe, 0xec, 0x60, 0xa5, 0xab, 0x6a, 0xbc,
	0x03, 0x70, 0xb2, 0x3f, 0xa7, 0xf2, 0x95, 0x91, 0x14, 0xcd, 0xc1, 0x0b, 0xb1, 0xdf, 0x24, 0x53,
	0xa9, 0x28, 0xfb, 0x7b, 0x9c, 0x1a, 0x0c, 0xce, 0xf7, 0xd3, 0x52, 0xae, 0x3f, 0x51, 0xd8, 0x2e,
	0xc3, 0xbd, 0xef, 0x04, 0xa9, 0x77, 0x7e, 0x06, 0x70, 0xe1, 0x0f, 0x2e, 0xfd, 0x37, 0x13, 0x99,
	0xfd, 0x36, 0x08, 0xcf, 0x48, 0x75, 0xe8, 0x13, 0x80, 0x03, 0xd1, 0xe2, 0x21, 0x9c, 0xfa, 0x6f,
	0x3a, 0xbe, 0xf5, 0xda, 0xad, 0xec, 0x80, 0xc8, 0x97, 0x31, 0xfd, 0xf6, 0xcb, 0xcf, 0x8f, 0xc5,
	0x09, 0x34, 0x8e, 0x63, 0xe4, 0x4d, 0x05, 0xc5, 0x6d, 0x28, 0x4e, 0x24, 0x0e, 0xfa, 0x05, 0xe0,
	0xa5, 0xd4, 0x4d, 0x46, 0x2b, 0xfd, 0x15, 0x64, 0x09, 0x0e, 0xed, 0x7e, 0x6e, 0x1e, 0x65, 0x70,
	0x45, 0x1a, 0x5c, 0x44, 0x77, 0xd3, 0x0d, 0xb2, 0x0e, 0x99, 0xe5, 0x08, 0xd7, 0x52, 0xaf, 0x6a,
	0x75, 0xb2, 0x03, 0xb5, 0x00, 0x2c, 0xf5, 0xca, 0x03, 0xb4, 0x74, 0x1a, 0xb5, 0x27, 0x66, 0x8e,
	0x56, 0xce, 0x43, 0xa1, 0xbc, 0x2e, 0x4a, 0xaf, 0x77, 0xd0, 0x7c, 0x66, 0xaf, 0x2c, 0x22, 0xb2,
	0x54, 0xf0, 0xa0, 0x37, 0x45, 0x38, 0x9a, 0x32, 0x57, 0xb4, 0x9c, 0xeb, 0x59, 0x62, 0xaf, 0xf7,
	0x72, 0xb2, 0x28, 0xbb, 0xeb, 0xd2, 0xee, 0x43, 0xb4, 0x9a, 0xe7, 0x69, 0xf1, 0xab, 0xe4, 0x06,
	0x1f, 0xa0, 0x46, 0x11, 0x4e, 0x9f, 0x26, 0x23, 0xd0, 0x7a, 0x2e, 0x3b, 0xbd, 0x82, 0x4e, 0xdb,
	0xf8, 0xdb, 0xb4, 0x6a, 0x6c, 0xbb, 0x72, 0x6c, 0x5b, 0xc8, 0xcf, 0x33, 0x36, 0xcb, 0xa9, 0x5b,
	0x31, 0xfc, 0x68, 0x94, 0x27, 0x87, 0xdb, 0x41, 0xf9, 0xc1, 0x61, 0x53, 0x07, 0x8d, 0xa6, 0x0e,
	0x7e, 0x34, 0x75, 0xf0, 0xa1, 0xa5, 0x17, 0x1a, 0x2d, 0xbd, 0xf0, 0xb5, 0xa5, 0x17, 0x9e, 0x61,
	0xcf, 0x17, 0x9b, 0x35, 0xc7, 0x74, 0xe9, 0x4e, 0x0f, 0x39, 0xfb, 0xb1, 0x20, 0x51, 0x0f, 0x09,
	0x77, 0x06, 0xe4, 0x57, 0xcf, 0xed, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xf3, 0x6d, 0x5a,
	0xae, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of RegisteredBtcDepositAddresses items.
	RegisteredBtcDepositAddresses(ctx context.Context, in *QueryRegisteredBtcDepositAddressesRequest, opts ...grpc.CallOption) (*QueryRegisteredBtcDepositAddressesResponse, error)
	// Queries a list of RegisteredReserveScripts items.
	RegisteredReserveScripts(ctx context.Context, in *QueryRegisteredReserveScriptsRequest, opts ...grpc.CallOption) (*QueryRegisteredReserveScriptsResponse, error)
	// Queries a list of RegisteredBtcDepositAddress items.
	RegisteredBtcDepositAddress(ctx context.Context, in *QueryRegisteredBtcDepositAddressRequest, opts ...grpc.CallOption) (*QueryRegisteredBtcDepositAddressResponse, error)
	// Queries a list of RegisteredBtcDepositAddressByTwilightAddress items.
	RegisteredBtcDepositAddressByTwilightAddress(ctx context.Context, in *QueryRegisteredBtcDepositAddressByTwilightAddressRequest, opts ...grpc.CallOption) (*QueryRegisteredBtcDepositAddressByTwilightAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.bridge.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredBtcDepositAddresses(ctx context.Context, in *QueryRegisteredBtcDepositAddressesRequest, opts ...grpc.CallOption) (*QueryRegisteredBtcDepositAddressesResponse, error) {
	out := new(QueryRegisteredBtcDepositAddressesResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.bridge.Query/RegisteredBtcDepositAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredReserveScripts(ctx context.Context, in *QueryRegisteredReserveScriptsRequest, opts ...grpc.CallOption) (*QueryRegisteredReserveScriptsResponse, error) {
	out := new(QueryRegisteredReserveScriptsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.bridge.Query/RegisteredReserveScripts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredBtcDepositAddress(ctx context.Context, in *QueryRegisteredBtcDepositAddressRequest, opts ...grpc.CallOption) (*QueryRegisteredBtcDepositAddressResponse, error) {
	out := new(QueryRegisteredBtcDepositAddressResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.bridge.Query/RegisteredBtcDepositAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegisteredBtcDepositAddressByTwilightAddress(ctx context.Context, in *QueryRegisteredBtcDepositAddressByTwilightAddressRequest, opts ...grpc.CallOption) (*QueryRegisteredBtcDepositAddressByTwilightAddressResponse, error) {
	out := new(QueryRegisteredBtcDepositAddressByTwilightAddressResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.bridge.Query/RegisteredBtcDepositAddressByTwilightAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of RegisteredBtcDepositAddresses items.
	RegisteredBtcDepositAddresses(context.Context, *QueryRegisteredBtcDepositAddressesRequest) (*QueryRegisteredBtcDepositAddressesResponse, error)
	// Queries a list of RegisteredReserveScripts items.
	RegisteredReserveScripts(context.Context, *QueryRegisteredReserveScriptsRequest) (*QueryRegisteredReserveScriptsResponse, error)
	// Queries a list of RegisteredBtcDepositAddress items.
	RegisteredBtcDepositAddress(context.Context, *QueryRegisteredBtcDepositAddressRequest) (*QueryRegisteredBtcDepositAddressResponse, error)
	// Queries a list of RegisteredBtcDepositAddressByTwilightAddress items.
	RegisteredBtcDepositAddressByTwilightAddress(context.Context, *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) (*QueryRegisteredBtcDepositAddressByTwilightAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RegisteredBtcDepositAddresses(ctx context.Context, req *QueryRegisteredBtcDepositAddressesRequest) (*QueryRegisteredBtcDepositAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredBtcDepositAddresses not implemented")
}
func (*UnimplementedQueryServer) RegisteredReserveScripts(ctx context.Context, req *QueryRegisteredReserveScriptsRequest) (*QueryRegisteredReserveScriptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredReserveScripts not implemented")
}
func (*UnimplementedQueryServer) RegisteredBtcDepositAddress(ctx context.Context, req *QueryRegisteredBtcDepositAddressRequest) (*QueryRegisteredBtcDepositAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredBtcDepositAddress not implemented")
}
func (*UnimplementedQueryServer) RegisteredBtcDepositAddressByTwilightAddress(ctx context.Context, req *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) (*QueryRegisteredBtcDepositAddressByTwilightAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisteredBtcDepositAddressByTwilightAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.bridge.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredBtcDepositAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegisteredBtcDepositAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredBtcDepositAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.bridge.Query/RegisteredBtcDepositAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredBtcDepositAddresses(ctx, req.(*QueryRegisteredBtcDepositAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredReserveScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegisteredReserveScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredReserveScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.bridge.Query/RegisteredReserveScripts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredReserveScripts(ctx, req.(*QueryRegisteredReserveScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredBtcDepositAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegisteredBtcDepositAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredBtcDepositAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.bridge.Query/RegisteredBtcDepositAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredBtcDepositAddress(ctx, req.(*QueryRegisteredBtcDepositAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegisteredBtcDepositAddressByTwilightAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegisteredBtcDepositAddressByTwilightAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegisteredBtcDepositAddressByTwilightAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.bridge.Query/RegisteredBtcDepositAddressByTwilightAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegisteredBtcDepositAddressByTwilightAddress(ctx, req.(*QueryRegisteredBtcDepositAddressByTwilightAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.bridge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RegisteredBtcDepositAddresses",
			Handler:    _Query_RegisteredBtcDepositAddresses_Handler,
		},
		{
			MethodName: "RegisteredReserveScripts",
			Handler:    _Query_RegisteredReserveScripts_Handler,
		},
		{
			MethodName: "RegisteredBtcDepositAddress",
			Handler:    _Query_RegisteredBtcDepositAddress_Handler,
		},
		{
			MethodName: "RegisteredBtcDepositAddressByTwilightAddress",
			Handler:    _Query_RegisteredBtcDepositAddressByTwilightAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bridge/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredBtcDepositAddressesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredBtcDepositAddressesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredBtcDepositAddressesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredBtcDepositAddressesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredBtcDepositAddressesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredBtcDepositAddressesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Addresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredReserveScriptsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredReserveScriptsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredReserveScriptsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredReserveScriptsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredReserveScriptsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredReserveScriptsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Scripts) > 0 {
		for iNdEx := len(m.Scripts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Scripts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredBtcDepositAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredBtcDepositAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredBtcDepositAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepositAddress) > 0 {
		i -= len(m.DepositAddress)
		copy(dAtA[i:], m.DepositAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DepositAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredBtcDepositAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredBtcDepositAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredBtcDepositAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TwilightDepositAddress) > 0 {
		i -= len(m.TwilightDepositAddress)
		copy(dAtA[i:], m.TwilightDepositAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TwilightDepositAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DepositAddress) > 0 {
		i -= len(m.DepositAddress)
		copy(dAtA[i:], m.DepositAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DepositAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TwilightDepositAddress) > 0 {
		i -= len(m.TwilightDepositAddress)
		copy(dAtA[i:], m.TwilightDepositAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TwilightDepositAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TwilightDepositAddress) > 0 {
		i -= len(m.TwilightDepositAddress)
		copy(dAtA[i:], m.TwilightDepositAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TwilightDepositAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DepositAddress) > 0 {
		i -= len(m.DepositAddress)
		copy(dAtA[i:], m.DepositAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DepositAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRegisteredBtcDepositAddressesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRegisteredBtcDepositAddressesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, e := range m.Addresses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryRegisteredReserveScriptsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRegisteredReserveScriptsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Scripts) > 0 {
		for _, e := range m.Scripts {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryRegisteredBtcDepositAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DepositAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegisteredBtcDepositAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DepositAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TwilightDepositAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TwilightDepositAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DepositAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TwilightDepositAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredBtcDepositAddressesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredBtcDepositAddressesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, MsgRegisterBtcDepositAddress{})
			if err := m.Addresses[len(m.Addresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredReserveScriptsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredReserveScriptsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredReserveScriptsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredReserveScriptsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredReserveScriptsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredReserveScriptsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scripts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scripts = append(m.Scripts, MsgRegisterReserveAddress{})
			if err := m.Scripts[len(m.Scripts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredBtcDepositAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredBtcDepositAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightDepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightDepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressByTwilightAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressByTwilightAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightDepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightDepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegisteredBtcDepositAddressByTwilightAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressByTwilightAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegisteredBtcDepositAddressByTwilightAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightDepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightDepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
