syntax = "proto3";

package twilightproject.nyks.fragment;

import "nyks/volt/reserve.proto";

option go_package = "github.com/twilight-project/nyks/x/fragment/types";

// Msg defines the Msg service.
service Msg {
  rpc SignerApplication (MsgSignerApplication) returns (MsgSignerApplicationResponse);
  rpc AcceptSigners     (MsgAcceptSigners    ) returns (MsgAcceptSignersResponse    );
}
message MsgSignerApplication {
  uint64  fragmentId     = 2;
  uint64  applicationFee = 3;
  string btcPubKey      = 4;
  string signerAddress  = 5;
}

message MsgSignerApplicationResponse {}

message MsgAcceptSigners {
  int32  fragmentId      = 2;
  string signerAddresses = 3;
  string judgeAddress    = 4;
}

message MsgAcceptSignersResponse {}

message Fragment {
    string FragmentID = 1;
    bool FragmentStatus = 2;
    string JudgeAddress = 3;
    string JudgeStatus = 4;
    repeated fragmentSigners Signers = 5;
    uint64 FeePool = 6;
    repeated twilightproject.nyks.volt.BtcReserve Reserves = 7;
}

message fragmentSigners {
    string fragmentID = 1;
    string signerAddress = 2;
	string signerStatus = 3;
    string signerBTCPublicKey = 4;
    uint32 signerApplicationFee = 5;
}