// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nyks/forks/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetDelegateAddresses struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	BtcOracleAddress string `protobuf:"bytes,2,opt,name=btcOracleAddress,proto3" json:"btcOracleAddress,omitempty"`
	BtcPublicKey     string `protobuf:"bytes,3,opt,name=btcPublicKey,proto3" json:"btcPublicKey,omitempty"`
	ZkOracleAddress  string `protobuf:"bytes,4,opt,name=zkOracleAddress,proto3" json:"zkOracleAddress,omitempty"`
}

func (m *MsgSetDelegateAddresses) Reset()         { *m = MsgSetDelegateAddresses{} }
func (m *MsgSetDelegateAddresses) String() string { return proto.CompactTextString(m) }
func (*MsgSetDelegateAddresses) ProtoMessage()    {}
func (*MsgSetDelegateAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c917796e634d2b6, []int{0}
}
func (m *MsgSetDelegateAddresses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetDelegateAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetDelegateAddresses.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetDelegateAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetDelegateAddresses.Merge(m, src)
}
func (m *MsgSetDelegateAddresses) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetDelegateAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetDelegateAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetDelegateAddresses proto.InternalMessageInfo

func (m *MsgSetDelegateAddresses) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *MsgSetDelegateAddresses) GetBtcOracleAddress() string {
	if m != nil {
		return m.BtcOracleAddress
	}
	return ""
}

func (m *MsgSetDelegateAddresses) GetBtcPublicKey() string {
	if m != nil {
		return m.BtcPublicKey
	}
	return ""
}

func (m *MsgSetDelegateAddresses) GetZkOracleAddress() string {
	if m != nil {
		return m.ZkOracleAddress
	}
	return ""
}

type MsgSetDelegateAddressesResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgSetDelegateAddressesResponse) Reset()         { *m = MsgSetDelegateAddressesResponse{} }
func (m *MsgSetDelegateAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetDelegateAddressesResponse) ProtoMessage()    {}
func (*MsgSetDelegateAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c917796e634d2b6, []int{1}
}
func (m *MsgSetDelegateAddressesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetDelegateAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetDelegateAddressesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetDelegateAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetDelegateAddressesResponse.Merge(m, src)
}
func (m *MsgSetDelegateAddressesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetDelegateAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetDelegateAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetDelegateAddressesResponse proto.InternalMessageInfo

func (m *MsgSetDelegateAddressesResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgSeenBtcChainTip struct {
	Height           uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash             string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	BtcOracleAddress string `protobuf:"bytes,3,opt,name=btcOracleAddress,proto3" json:"btcOracleAddress,omitempty"`
}

func (m *MsgSeenBtcChainTip) Reset()         { *m = MsgSeenBtcChainTip{} }
func (m *MsgSeenBtcChainTip) String() string { return proto.CompactTextString(m) }
func (*MsgSeenBtcChainTip) ProtoMessage()    {}
func (*MsgSeenBtcChainTip) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c917796e634d2b6, []int{2}
}
func (m *MsgSeenBtcChainTip) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSeenBtcChainTip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSeenBtcChainTip.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSeenBtcChainTip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSeenBtcChainTip.Merge(m, src)
}
func (m *MsgSeenBtcChainTip) XXX_Size() int {
	return m.Size()
}
func (m *MsgSeenBtcChainTip) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSeenBtcChainTip.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSeenBtcChainTip proto.InternalMessageInfo

func (m *MsgSeenBtcChainTip) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *MsgSeenBtcChainTip) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *MsgSeenBtcChainTip) GetBtcOracleAddress() string {
	if m != nil {
		return m.BtcOracleAddress
	}
	return ""
}

type MsgSeenBtcChainTipResponse struct {
}

func (m *MsgSeenBtcChainTipResponse) Reset()         { *m = MsgSeenBtcChainTipResponse{} }
func (m *MsgSeenBtcChainTipResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSeenBtcChainTipResponse) ProtoMessage()    {}
func (*MsgSeenBtcChainTipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c917796e634d2b6, []int{3}
}
func (m *MsgSeenBtcChainTipResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSeenBtcChainTipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSeenBtcChainTipResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSeenBtcChainTipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSeenBtcChainTipResponse.Merge(m, src)
}
func (m *MsgSeenBtcChainTipResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSeenBtcChainTipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSeenBtcChainTipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSeenBtcChainTipResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetDelegateAddresses)(nil), "twilightproject.nyks.forks.MsgSetDelegateAddresses")
	proto.RegisterType((*MsgSetDelegateAddressesResponse)(nil), "twilightproject.nyks.forks.MsgSetDelegateAddressesResponse")
	proto.RegisterType((*MsgSeenBtcChainTip)(nil), "twilightproject.nyks.forks.MsgSeenBtcChainTip")
	proto.RegisterType((*MsgSeenBtcChainTipResponse)(nil), "twilightproject.nyks.forks.MsgSeenBtcChainTipResponse")
}

func init() { proto.RegisterFile("nyks/forks/tx.proto", fileDescriptor_1c917796e634d2b6) }

var fileDescriptor_1c917796e634d2b6 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xbb, 0x69, 0x29, 0x38, 0x88, 0x95, 0x55, 0xb4, 0x04, 0x89, 0x92, 0x53, 0x11, 0xdc,
	0xa0, 0x05, 0x2f, 0x9e, 0xac, 0x1e, 0x04, 0x29, 0x4a, 0xf5, 0xe4, 0x2d, 0xd9, 0xac, 0xc9, 0xda,
	0x98, 0x0d, 0xd9, 0xad, 0x36, 0x3e, 0x81, 0xe0, 0xc5, 0x37, 0xf2, 0xea, 0xb1, 0x47, 0x8f, 0xd2,
	0xbe, 0x88, 0x74, 0x4d, 0x84, 0xfe, 0x43, 0xf4, 0x96, 0x7c, 0xfc, 0xf6, 0x9b, 0xf9, 0x66, 0x06,
	0xd6, 0xe2, 0xac, 0x2b, 0x9d, 0x5b, 0x91, 0x76, 0xa5, 0xa3, 0xfa, 0x24, 0x49, 0x85, 0x12, 0xd8,
	0x54, 0x8f, 0x3c, 0xe2, 0x41, 0xa8, 0x92, 0x54, 0xdc, 0x31, 0xaa, 0xc8, 0x18, 0x22, 0x1a, 0xb2,
	0xdf, 0x10, 0x6c, 0xb6, 0x65, 0x70, 0xc5, 0xd4, 0x29, 0x8b, 0x58, 0xe0, 0x2a, 0x76, 0xec, 0xfb,
	0x29, 0x93, 0x92, 0x49, 0xbc, 0x0b, 0xab, 0x0f, 0x6e, 0xc4, 0x7d, 0x57, 0x89, 0x34, 0x57, 0xeb,
	0x68, 0x07, 0x35, 0x96, 0x3a, 0x33, 0xfa, 0x98, 0xf5, 0x14, 0xbd, 0x48, 0x5d, 0x1a, 0x15, 0x0e,
	0x75, 0xe3, 0x9b, 0x9d, 0xd6, 0xb1, 0x0d, 0xcb, 0x9e, 0xa2, 0x97, 0x3d, 0x2f, 0xe2, 0xf4, 0x9c,
	0x65, 0xf5, 0xb2, 0xe6, 0x26, 0x34, 0xdc, 0x80, 0xda, 0x53, 0x77, 0xd2, 0xae, 0xa2, 0xb1, 0x69,
	0xd9, 0xde, 0x87, 0xed, 0x05, 0x01, 0x3a, 0x4c, 0x26, 0x22, 0x96, 0x0c, 0xaf, 0x80, 0xc1, 0x7d,
	0xdd, 0x7a, 0xa5, 0x63, 0x70, 0xdf, 0x8e, 0x00, 0xeb, 0x27, 0x2c, 0x6e, 0x29, 0x7a, 0x12, 0xba,
	0x3c, 0xbe, 0xe6, 0x09, 0xde, 0x80, 0x6a, 0xc8, 0xc6, 0x63, 0xca, 0xc9, 0xfc, 0x0f, 0x63, 0xa8,
	0x84, 0xae, 0x0c, 0xf3, 0x38, 0xfa, 0x7b, 0x6e, 0xdc, 0xf2, 0xfc, 0xb8, 0xf6, 0x16, 0x98, 0xb3,
	0xd5, 0x8a, 0xde, 0x0e, 0x5e, 0x0c, 0x28, 0xb7, 0x65, 0x80, 0x9f, 0x11, 0xac, 0xcf, 0xdd, 0x42,
	0x93, 0x2c, 0x5e, 0x1f, 0x59, 0x90, 0xdc, 0x3c, 0xfa, 0xc7, 0xa3, 0x9f, 0x71, 0x65, 0x50, 0x9b,
	0x9e, 0x0d, 0xf9, 0xd5, 0x6f, 0x82, 0x37, 0x0f, 0xff, 0xc6, 0x17, 0xa5, 0x5b, 0x67, 0xef, 0x43,
	0x0b, 0x0d, 0x86, 0x16, 0xfa, 0x1c, 0x5a, 0xe8, 0x75, 0x64, 0x95, 0x06, 0x23, 0xab, 0xf4, 0x31,
	0xb2, 0x4a, 0x37, 0x24, 0xe0, 0x2a, 0xec, 0x79, 0x84, 0x8a, 0x7b, 0xa7, 0xf0, 0xde, 0xcb, 0xcd,
	0x1d, 0x7d, 0xf5, 0xfd, 0xe2, 0xee, 0xb3, 0x84, 0x49, 0xaf, 0xaa, 0x6f, 0xbf, 0xf9, 0x15, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x41, 0xd1, 0x76, 0x12, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetDelegateAddresses(ctx context.Context, in *MsgSetDelegateAddresses, opts ...grpc.CallOption) (*MsgSetDelegateAddressesResponse, error)
	SeenBtcChainTip(ctx context.Context, in *MsgSeenBtcChainTip, opts ...grpc.CallOption) (*MsgSeenBtcChainTipResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetDelegateAddresses(ctx context.Context, in *MsgSetDelegateAddresses, opts ...grpc.CallOption) (*MsgSetDelegateAddressesResponse, error) {
	out := new(MsgSetDelegateAddressesResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Msg/SetDelegateAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SeenBtcChainTip(ctx context.Context, in *MsgSeenBtcChainTip, opts ...grpc.CallOption) (*MsgSeenBtcChainTipResponse, error) {
	out := new(MsgSeenBtcChainTipResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Msg/SeenBtcChainTip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetDelegateAddresses(context.Context, *MsgSetDelegateAddresses) (*MsgSetDelegateAddressesResponse, error)
	SeenBtcChainTip(context.Context, *MsgSeenBtcChainTip) (*MsgSeenBtcChainTipResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetDelegateAddresses(ctx context.Context, req *MsgSetDelegateAddresses) (*MsgSetDelegateAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDelegateAddresses not implemented")
}
func (*UnimplementedMsgServer) SeenBtcChainTip(ctx context.Context, req *MsgSeenBtcChainTip) (*MsgSeenBtcChainTipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeenBtcChainTip not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetDelegateAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetDelegateAddresses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetDelegateAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Msg/SetDelegateAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetDelegateAddresses(ctx, req.(*MsgSetDelegateAddresses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SeenBtcChainTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSeenBtcChainTip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SeenBtcChainTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Msg/SeenBtcChainTip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SeenBtcChainTip(ctx, req.(*MsgSeenBtcChainTip))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.forks.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetDelegateAddresses",
			Handler:    _Msg_SetDelegateAddresses_Handler,
		},
		{
			MethodName: "SeenBtcChainTip",
			Handler:    _Msg_SeenBtcChainTip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nyks/forks/tx.proto",
}

func (m *MsgSetDelegateAddresses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetDelegateAddresses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetDelegateAddresses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ZkOracleAddress) > 0 {
		i -= len(m.ZkOracleAddress)
		copy(dAtA[i:], m.ZkOracleAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZkOracleAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BtcPublicKey) > 0 {
		i -= len(m.BtcPublicKey)
		copy(dAtA[i:], m.BtcPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcPublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BtcOracleAddress) > 0 {
		i -= len(m.BtcOracleAddress)
		copy(dAtA[i:], m.BtcOracleAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcOracleAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetDelegateAddressesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetDelegateAddressesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetDelegateAddressesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSeenBtcChainTip) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSeenBtcChainTip) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSeenBtcChainTip) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BtcOracleAddress) > 0 {
		i -= len(m.BtcOracleAddress)
		copy(dAtA[i:], m.BtcOracleAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcOracleAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSeenBtcChainTipResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSeenBtcChainTipResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSeenBtcChainTipResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetDelegateAddresses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BtcOracleAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BtcPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ZkOracleAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetDelegateAddressesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgSeenBtcChainTip) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BtcOracleAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSeenBtcChainTipResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetDelegateAddresses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetDelegateAddresses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetDelegateAddresses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetDelegateAddressesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetDelegateAddressesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetDelegateAddressesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSeenBtcChainTip) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSeenBtcChainTip: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSeenBtcChainTip: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSeenBtcChainTipResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSeenBtcChainTipResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSeenBtcChainTipResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
