version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 100000000nyks
  - 0sats
- name: bob
  coins:
  - 100000000nyks
  - 0sats
faucet:
  name: bob
  coins:
  - 100000nyks
  - 1sats
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    mint:
      params:
        mint_denom: nyks
    staking:
      params:
        bond_denom: nyks
validators:
- name: alice
  bonded: 100000000nyks
  home: $HOME/.nyks
