accounts:
  - name: alice
    coins: ["100000000nyks", "0btc"]
  - name: bob
    coins: ["100000000nyks", "0btc"]
validator:
  name: alice
  staked: "100000000nyks"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000nyks", "1btc"]
genesis:
  chain_id: "nyks"
init:
  home: "$HOME/.nyks"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "nyks" 
    mint:
      params:
        mint_denom: nyks    
