// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgSignerApplication } from "./types/nyks/volt/fragment";
import { MsgAcceptSigners } from "./types/nyks/volt/fragment";

import { IndividualTwilightReserveAccountBalance as typeIndividualTwilightReserveAccountBalance} from "./types"
import { ClearingAccount as typeClearingAccount} from "./types"
import { RefundTxAccountSnap as typeRefundTxAccountSnap} from "./types"
import { RefundTxSnapshot as typeRefundTxSnapshot} from "./types"
import { BtcDepositAddress as typeBtcDepositAddress} from "./types"
import { EventReserveWithdrawSnapshot as typeEventReserveWithdrawSnapshot} from "./types"
import { EventRefundTxSnapshot as typeEventRefundTxSnapshot} from "./types"
import { EventAcceptSigners as typeEventAcceptSigners} from "./types"
import { SignerInfo as typeSignerInfo} from "./types"
import { Fragment as typeFragment} from "./types"
import { FragmentSigners as typeFragmentSigners} from "./types"
import { Params as typeParams} from "./types"
import { BtcReserve as typeBtcReserve} from "./types"
import { BtcWithdrawRequestInternal as typeBtcWithdrawRequestInternal} from "./types"
import { ReserveWithdrawPool as typeReserveWithdrawPool} from "./types"
import { WithdrawRequestSnap as typeWithdrawRequestSnap} from "./types"
import { ReserveWithdrawSnapshot as typeReserveWithdrawSnapshot} from "./types"
import { NewSweepProposalReceivedInternal as typeNewSweepProposalReceivedInternal} from "./types"

export { MsgSignerApplication, MsgAcceptSigners };

type sendMsgSignerApplicationParams = {
  value: MsgSignerApplication,
  fee?: StdFee,
  memo?: string
};

type sendMsgAcceptSignersParams = {
  value: MsgAcceptSigners,
  fee?: StdFee,
  memo?: string
};


type msgSignerApplicationParams = {
  value: MsgSignerApplication,
};

type msgAcceptSignersParams = {
  value: MsgAcceptSigners,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgSignerApplication({ value, fee, memo }: sendMsgSignerApplicationParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSignerApplication: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSignerApplication({ value: MsgSignerApplication.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSignerApplication: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAcceptSigners({ value, fee, memo }: sendMsgAcceptSignersParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAcceptSigners: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAcceptSigners({ value: MsgAcceptSigners.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAcceptSigners: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgSignerApplication({ value }: msgSignerApplicationParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.volt.MsgSignerApplication", value: MsgSignerApplication.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSignerApplication: Could not create message: ' + e.message)
			}
		},
		
		msgAcceptSigners({ value }: msgAcceptSignersParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.volt.MsgAcceptSigners", value: MsgAcceptSigners.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAcceptSigners: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						IndividualTwilightReserveAccountBalance: getStructure(typeIndividualTwilightReserveAccountBalance.fromPartial({})),
						ClearingAccount: getStructure(typeClearingAccount.fromPartial({})),
						RefundTxAccountSnap: getStructure(typeRefundTxAccountSnap.fromPartial({})),
						RefundTxSnapshot: getStructure(typeRefundTxSnapshot.fromPartial({})),
						BtcDepositAddress: getStructure(typeBtcDepositAddress.fromPartial({})),
						EventReserveWithdrawSnapshot: getStructure(typeEventReserveWithdrawSnapshot.fromPartial({})),
						EventRefundTxSnapshot: getStructure(typeEventRefundTxSnapshot.fromPartial({})),
						EventAcceptSigners: getStructure(typeEventAcceptSigners.fromPartial({})),
						SignerInfo: getStructure(typeSignerInfo.fromPartial({})),
						Fragment: getStructure(typeFragment.fromPartial({})),
						FragmentSigners: getStructure(typeFragmentSigners.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						BtcReserve: getStructure(typeBtcReserve.fromPartial({})),
						BtcWithdrawRequestInternal: getStructure(typeBtcWithdrawRequestInternal.fromPartial({})),
						ReserveWithdrawPool: getStructure(typeReserveWithdrawPool.fromPartial({})),
						WithdrawRequestSnap: getStructure(typeWithdrawRequestSnap.fromPartial({})),
						ReserveWithdrawSnapshot: getStructure(typeReserveWithdrawSnapshot.fromPartial({})),
						NewSweepProposalReceivedInternal: getStructure(typeNewSweepProposalReceivedInternal.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			TwilightprojectNyksVolt: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;