// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nyks/volt/withdraw.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Chain creates an internal mapping with identifier and bool confirmed
type BtcWithdrawRequestInternal struct {
	WithdrawIdentifier          uint32 `protobuf:"varint,1,opt,name=withdrawIdentifier,proto3" json:"withdrawIdentifier,omitempty"`
	WithdrawAddress             string `protobuf:"bytes,2,opt,name=withdrawAddress,proto3" json:"withdrawAddress,omitempty"`
	WithdrawReserveId           uint64 `protobuf:"varint,3,opt,name=withdrawReserveId,proto3" json:"withdrawReserveId,omitempty"`
	WithdrawAmount              uint64 `protobuf:"varint,4,opt,name=withdrawAmount,proto3" json:"withdrawAmount,omitempty"`
	TwilightAddress             string `protobuf:"bytes,5,opt,name=twilightAddress,proto3" json:"twilightAddress,omitempty"`
	IsConfirmed                 bool   `protobuf:"varint,6,opt,name=isConfirmed,proto3" json:"isConfirmed,omitempty"`
	CreationTwilightBlockHeight int64  `protobuf:"varint,7,opt,name=CreationTwilightBlockHeight,proto3" json:"CreationTwilightBlockHeight,omitempty"`
}

func (m *BtcWithdrawRequestInternal) Reset()         { *m = BtcWithdrawRequestInternal{} }
func (m *BtcWithdrawRequestInternal) String() string { return proto.CompactTextString(m) }
func (*BtcWithdrawRequestInternal) ProtoMessage()    {}
func (*BtcWithdrawRequestInternal) Descriptor() ([]byte, []int) {
	return fileDescriptor_f90771821fadb56e, []int{0}
}
func (m *BtcWithdrawRequestInternal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BtcWithdrawRequestInternal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BtcWithdrawRequestInternal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BtcWithdrawRequestInternal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BtcWithdrawRequestInternal.Merge(m, src)
}
func (m *BtcWithdrawRequestInternal) XXX_Size() int {
	return m.Size()
}
func (m *BtcWithdrawRequestInternal) XXX_DiscardUnknown() {
	xxx_messageInfo_BtcWithdrawRequestInternal.DiscardUnknown(m)
}

var xxx_messageInfo_BtcWithdrawRequestInternal proto.InternalMessageInfo

func (m *BtcWithdrawRequestInternal) GetWithdrawIdentifier() uint32 {
	if m != nil {
		return m.WithdrawIdentifier
	}
	return 0
}

func (m *BtcWithdrawRequestInternal) GetWithdrawAddress() string {
	if m != nil {
		return m.WithdrawAddress
	}
	return ""
}

func (m *BtcWithdrawRequestInternal) GetWithdrawReserveId() uint64 {
	if m != nil {
		return m.WithdrawReserveId
	}
	return 0
}

func (m *BtcWithdrawRequestInternal) GetWithdrawAmount() uint64 {
	if m != nil {
		return m.WithdrawAmount
	}
	return 0
}

func (m *BtcWithdrawRequestInternal) GetTwilightAddress() string {
	if m != nil {
		return m.TwilightAddress
	}
	return ""
}

func (m *BtcWithdrawRequestInternal) GetIsConfirmed() bool {
	if m != nil {
		return m.IsConfirmed
	}
	return false
}

func (m *BtcWithdrawRequestInternal) GetCreationTwilightBlockHeight() int64 {
	if m != nil {
		return m.CreationTwilightBlockHeight
	}
	return 0
}

type ReserveWithdrawPool struct {
	ReserveID                     uint64   `protobuf:"varint,1,opt,name=ReserveID,proto3" json:"ReserveID,omitempty"`
	RoundID                       uint64   `protobuf:"varint,2,opt,name=RoundID,proto3" json:"RoundID,omitempty"`
	ProcessingWithdrawIdentifiers []uint32 `protobuf:"varint,3,rep,packed,name=processingWithdrawIdentifiers,proto3" json:"processingWithdrawIdentifiers,omitempty"`
	QueuedWithdrawIdentifiers     []uint32 `protobuf:"varint,4,rep,packed,name=queuedWithdrawIdentifiers,proto3" json:"queuedWithdrawIdentifiers,omitempty"`
	CurrentProcessingIndex        uint32   `protobuf:"varint,5,opt,name=currentProcessingIndex,proto3" json:"currentProcessingIndex,omitempty"`
}

func (m *ReserveWithdrawPool) Reset()         { *m = ReserveWithdrawPool{} }
func (m *ReserveWithdrawPool) String() string { return proto.CompactTextString(m) }
func (*ReserveWithdrawPool) ProtoMessage()    {}
func (*ReserveWithdrawPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_f90771821fadb56e, []int{1}
}
func (m *ReserveWithdrawPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReserveWithdrawPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReserveWithdrawPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReserveWithdrawPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveWithdrawPool.Merge(m, src)
}
func (m *ReserveWithdrawPool) XXX_Size() int {
	return m.Size()
}
func (m *ReserveWithdrawPool) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveWithdrawPool.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveWithdrawPool proto.InternalMessageInfo

func (m *ReserveWithdrawPool) GetReserveID() uint64 {
	if m != nil {
		return m.ReserveID
	}
	return 0
}

func (m *ReserveWithdrawPool) GetRoundID() uint64 {
	if m != nil {
		return m.RoundID
	}
	return 0
}

func (m *ReserveWithdrawPool) GetProcessingWithdrawIdentifiers() []uint32 {
	if m != nil {
		return m.ProcessingWithdrawIdentifiers
	}
	return nil
}

func (m *ReserveWithdrawPool) GetQueuedWithdrawIdentifiers() []uint32 {
	if m != nil {
		return m.QueuedWithdrawIdentifiers
	}
	return nil
}

func (m *ReserveWithdrawPool) GetCurrentProcessingIndex() uint32 {
	if m != nil {
		return m.CurrentProcessingIndex
	}
	return 0
}

// WithdrawRequestSnap is a snapshot of the withdraw request
type WithdrawRequestSnap struct {
	WithdrawIdentifier uint32 `protobuf:"varint,1,opt,name=withdrawIdentifier,proto3" json:"withdrawIdentifier,omitempty"`
	WithdrawAddress    string `protobuf:"bytes,2,opt,name=withdrawAddress,proto3" json:"withdrawAddress,omitempty"`
	WithdrawAmount     uint64 `protobuf:"varint,3,opt,name=withdrawAmount,proto3" json:"withdrawAmount,omitempty"`
}

func (m *WithdrawRequestSnap) Reset()         { *m = WithdrawRequestSnap{} }
func (m *WithdrawRequestSnap) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequestSnap) ProtoMessage()    {}
func (*WithdrawRequestSnap) Descriptor() ([]byte, []int) {
	return fileDescriptor_f90771821fadb56e, []int{2}
}
func (m *WithdrawRequestSnap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WithdrawRequestSnap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WithdrawRequestSnap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WithdrawRequestSnap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequestSnap.Merge(m, src)
}
func (m *WithdrawRequestSnap) XXX_Size() int {
	return m.Size()
}
func (m *WithdrawRequestSnap) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequestSnap.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequestSnap proto.InternalMessageInfo

func (m *WithdrawRequestSnap) GetWithdrawIdentifier() uint32 {
	if m != nil {
		return m.WithdrawIdentifier
	}
	return 0
}

func (m *WithdrawRequestSnap) GetWithdrawAddress() string {
	if m != nil {
		return m.WithdrawAddress
	}
	return ""
}

func (m *WithdrawRequestSnap) GetWithdrawAmount() uint64 {
	if m != nil {
		return m.WithdrawAmount
	}
	return 0
}

// LastReserveWithdrawSnapshot is a snapshot of the last reserve withdraw
type LastReserveWithdrawSnapshot struct {
	ReserveId                uint64                 `protobuf:"varint,1,opt,name=ReserveId,proto3" json:"ReserveId,omitempty"`
	RoundId                  uint64                 `protobuf:"varint,2,opt,name=RoundId,proto3" json:"RoundId,omitempty"`
	WithdrawRequests         []*WithdrawRequestSnap `protobuf:"bytes,3,rep,name=withdrawRequests,proto3" json:"withdrawRequests,omitempty"`
	EndBlockerHeightTwilight int64                  `protobuf:"varint,4,opt,name=EndBlockerHeightTwilight,proto3" json:"EndBlockerHeightTwilight,omitempty"`
}

func (m *LastReserveWithdrawSnapshot) Reset()         { *m = LastReserveWithdrawSnapshot{} }
func (m *LastReserveWithdrawSnapshot) String() string { return proto.CompactTextString(m) }
func (*LastReserveWithdrawSnapshot) ProtoMessage()    {}
func (*LastReserveWithdrawSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_f90771821fadb56e, []int{3}
}
func (m *LastReserveWithdrawSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LastReserveWithdrawSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LastReserveWithdrawSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LastReserveWithdrawSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastReserveWithdrawSnapshot.Merge(m, src)
}
func (m *LastReserveWithdrawSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *LastReserveWithdrawSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_LastReserveWithdrawSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_LastReserveWithdrawSnapshot proto.InternalMessageInfo

func (m *LastReserveWithdrawSnapshot) GetReserveId() uint64 {
	if m != nil {
		return m.ReserveId
	}
	return 0
}

func (m *LastReserveWithdrawSnapshot) GetRoundId() uint64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *LastReserveWithdrawSnapshot) GetWithdrawRequests() []*WithdrawRequestSnap {
	if m != nil {
		return m.WithdrawRequests
	}
	return nil
}

func (m *LastReserveWithdrawSnapshot) GetEndBlockerHeightTwilight() int64 {
	if m != nil {
		return m.EndBlockerHeightTwilight
	}
	return 0
}

func init() {
	proto.RegisterType((*BtcWithdrawRequestInternal)(nil), "twilightproject.nyks.volt.BtcWithdrawRequestInternal")
	proto.RegisterType((*ReserveWithdrawPool)(nil), "twilightproject.nyks.volt.ReserveWithdrawPool")
	proto.RegisterType((*WithdrawRequestSnap)(nil), "twilightproject.nyks.volt.WithdrawRequestSnap")
	proto.RegisterType((*LastReserveWithdrawSnapshot)(nil), "twilightproject.nyks.volt.LastReserveWithdrawSnapshot")
}

func init() { proto.RegisterFile("nyks/volt/withdraw.proto", fileDescriptor_f90771821fadb56e) }

var fileDescriptor_f90771821fadb56e = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xae, 0x9b, 0xb2, 0x31, 0x4f, 0xe5, 0x87, 0x27, 0x21, 0x8f, 0x41, 0x14, 0xf5, 0x80, 0x72,
	0x60, 0xa9, 0x04, 0x12, 0x07, 0xc4, 0x01, 0xba, 0x22, 0x88, 0xc4, 0x61, 0x32, 0x48, 0x93, 0x76,
	0xcb, 0xe2, 0xb7, 0xd6, 0x2c, 0xb5, 0x33, 0xdb, 0x59, 0xb6, 0x3f, 0x81, 0x1b, 0x37, 0xfe, 0x25,
	0x8e, 0x3b, 0x22, 0x4e, 0xa8, 0x3d, 0xf3, 0x3f, 0xa0, 0xa4, 0x4d, 0xb7, 0xa5, 0xed, 0x6e, 0xdc,
	0x92, 0xf7, 0x3e, 0xbf, 0xe7, 0xf7, 0x7d, 0x9f, 0x1f, 0xa6, 0xf2, 0xe2, 0xc4, 0x74, 0xcf, 0x54,
	0x62, 0xbb, 0xb9, 0xb0, 0x43, 0xae, 0xa3, 0x3c, 0x48, 0xb5, 0xb2, 0x8a, 0x6c, 0xdb, 0x5c, 0x24,
	0x62, 0x30, 0xb4, 0xa9, 0x56, 0x5f, 0x21, 0xb6, 0x41, 0x81, 0x0c, 0x0a, 0x64, 0xe7, 0x77, 0x13,
	0x3f, 0xee, 0xd9, 0xf8, 0x60, 0x76, 0x80, 0xc1, 0x69, 0x06, 0xc6, 0x86, 0xd2, 0x82, 0x96, 0x51,
	0x42, 0x02, 0x4c, 0xaa, 0x5a, 0x21, 0x07, 0x69, 0xc5, 0xb1, 0x00, 0x4d, 0x91, 0x87, 0xfc, 0x36,
	0x5b, 0x92, 0x21, 0x3e, 0xbe, 0x5f, 0x45, 0xdf, 0x71, 0xae, 0xc1, 0x18, 0xda, 0xf4, 0x90, 0xbf,
	0xc1, 0xea, 0x61, 0xf2, 0x1c, 0x3f, 0xcc, 0xe7, 0x4d, 0x0d, 0xe8, 0x33, 0x08, 0x39, 0x75, 0x3c,
	0xe4, 0xb7, 0xd8, 0x62, 0x82, 0x3c, 0xc3, 0xf7, 0xe6, 0x05, 0x46, 0x2a, 0x93, 0x96, 0xb6, 0x4a,
	0x68, 0x2d, 0x5a, 0xf4, 0xaf, 0x66, 0xad, 0xfa, 0xdf, 0x99, 0xf6, 0xaf, 0x85, 0x89, 0x87, 0x37,
	0x85, 0xd9, 0x53, 0xf2, 0x58, 0xe8, 0x11, 0x70, 0xba, 0xe6, 0x21, 0xff, 0x2e, 0xbb, 0x1e, 0x22,
	0x6f, 0xf1, 0xce, 0x9e, 0x86, 0xc8, 0x0a, 0x25, 0xbf, 0xcc, 0x0e, 0xf7, 0x12, 0x15, 0x9f, 0x7c,
	0x84, 0xe2, 0x93, 0xae, 0x7b, 0xc8, 0x77, 0xd8, 0x6d, 0x90, 0xce, 0xb7, 0x26, 0xde, 0x9a, 0xcd,
	0x50, 0x11, 0xbc, 0xaf, 0x54, 0x42, 0x9e, 0xe0, 0x8d, 0x6a, 0xb4, 0x7e, 0x49, 0x66, 0x8b, 0x5d,
	0x05, 0x08, 0xc5, 0xeb, 0x4c, 0x65, 0x92, 0x87, 0xfd, 0x92, 0xbb, 0x16, 0xab, 0x7e, 0x49, 0x1f,
	0x3f, 0x4d, 0xb5, 0x8a, 0xc1, 0x18, 0x21, 0x07, 0x07, 0x0b, 0xec, 0x1b, 0xea, 0x78, 0x8e, 0xdf,
	0x66, 0xb7, 0x83, 0xc8, 0x1b, 0xbc, 0x7d, 0x9a, 0x41, 0x06, 0x7c, 0x59, 0x85, 0x56, 0x59, 0x61,
	0x35, 0x80, 0xbc, 0xc2, 0x8f, 0xe2, 0x4c, 0x6b, 0x90, 0x76, 0x7f, 0xde, 0x25, 0x94, 0x1c, 0xce,
	0x4b, 0xa2, 0xdb, 0x6c, 0x45, 0xb6, 0xf3, 0x03, 0xe1, 0xad, 0x9a, 0xcb, 0x3e, 0xcb, 0x28, 0xfd,
	0x8f, 0x0e, 0x5b, 0xf4, 0x8c, 0xb3, 0xcc, 0x33, 0x9d, 0xbf, 0x08, 0xef, 0x7c, 0x8a, 0x8c, 0xad,
	0x29, 0x55, 0xdc, 0xce, 0x0c, 0x95, 0xbd, 0xae, 0x16, 0xaf, 0xab, 0xc5, 0xaf, 0xd4, 0xe2, 0x37,
	0xd5, 0xe2, 0xe4, 0x10, 0x3f, 0xc8, 0x6f, 0x0e, 0x3c, 0x15, 0x68, 0xf3, 0x45, 0x10, 0xac, 0x7c,
	0x90, 0xc1, 0x12, 0x8e, 0xd8, 0x42, 0x1d, 0xf2, 0x1a, 0xd3, 0xf7, 0x92, 0x97, 0x5e, 0x03, 0x3d,
	0x75, 0x5b, 0x65, 0xc0, 0xf2, 0x65, 0x38, 0x6c, 0x65, 0xbe, 0xf7, 0xe1, 0xe7, 0xd8, 0x45, 0x97,
	0x63, 0x17, 0xfd, 0x19, 0xbb, 0xe8, 0xfb, 0xc4, 0x6d, 0x5c, 0x4e, 0xdc, 0xc6, 0xaf, 0x89, 0xdb,
	0x38, 0xdc, 0x1d, 0x08, 0x3b, 0xcc, 0x8e, 0x82, 0x58, 0x8d, 0xba, 0xd5, 0x0d, 0x77, 0x67, 0x57,
	0xec, 0x96, 0xdb, 0xe5, 0x7c, 0xba, 0x5f, 0xec, 0x45, 0x0a, 0xe6, 0x68, 0xad, 0xdc, 0x2e, 0x2f,
	0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xcb, 0x7c, 0x8a, 0x79, 0x04, 0x00, 0x00,
}

func (m *BtcWithdrawRequestInternal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BtcWithdrawRequestInternal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BtcWithdrawRequestInternal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreationTwilightBlockHeight != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.CreationTwilightBlockHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.IsConfirmed {
		i--
		if m.IsConfirmed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.TwilightAddress) > 0 {
		i -= len(m.TwilightAddress)
		copy(dAtA[i:], m.TwilightAddress)
		i = encodeVarintWithdraw(dAtA, i, uint64(len(m.TwilightAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if m.WithdrawAmount != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.WithdrawAmount))
		i--
		dAtA[i] = 0x20
	}
	if m.WithdrawReserveId != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.WithdrawReserveId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.WithdrawAddress) > 0 {
		i -= len(m.WithdrawAddress)
		copy(dAtA[i:], m.WithdrawAddress)
		i = encodeVarintWithdraw(dAtA, i, uint64(len(m.WithdrawAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.WithdrawIdentifier != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.WithdrawIdentifier))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReserveWithdrawPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReserveWithdrawPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReserveWithdrawPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentProcessingIndex != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.CurrentProcessingIndex))
		i--
		dAtA[i] = 0x28
	}
	if len(m.QueuedWithdrawIdentifiers) > 0 {
		dAtA2 := make([]byte, len(m.QueuedWithdrawIdentifiers)*10)
		var j1 int
		for _, num := range m.QueuedWithdrawIdentifiers {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintWithdraw(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProcessingWithdrawIdentifiers) > 0 {
		dAtA4 := make([]byte, len(m.ProcessingWithdrawIdentifiers)*10)
		var j3 int
		for _, num := range m.ProcessingWithdrawIdentifiers {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintWithdraw(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x1a
	}
	if m.RoundID != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.RoundID))
		i--
		dAtA[i] = 0x10
	}
	if m.ReserveID != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.ReserveID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *WithdrawRequestSnap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WithdrawRequestSnap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WithdrawRequestSnap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WithdrawAmount != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.WithdrawAmount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.WithdrawAddress) > 0 {
		i -= len(m.WithdrawAddress)
		copy(dAtA[i:], m.WithdrawAddress)
		i = encodeVarintWithdraw(dAtA, i, uint64(len(m.WithdrawAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.WithdrawIdentifier != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.WithdrawIdentifier))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LastReserveWithdrawSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LastReserveWithdrawSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LastReserveWithdrawSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndBlockerHeightTwilight != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.EndBlockerHeightTwilight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.WithdrawRequests) > 0 {
		for iNdEx := len(m.WithdrawRequests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawRequests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWithdraw(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.RoundId != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.RoundId))
		i--
		dAtA[i] = 0x10
	}
	if m.ReserveId != 0 {
		i = encodeVarintWithdraw(dAtA, i, uint64(m.ReserveId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintWithdraw(dAtA []byte, offset int, v uint64) int {
	offset -= sovWithdraw(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BtcWithdrawRequestInternal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WithdrawIdentifier != 0 {
		n += 1 + sovWithdraw(uint64(m.WithdrawIdentifier))
	}
	l = len(m.WithdrawAddress)
	if l > 0 {
		n += 1 + l + sovWithdraw(uint64(l))
	}
	if m.WithdrawReserveId != 0 {
		n += 1 + sovWithdraw(uint64(m.WithdrawReserveId))
	}
	if m.WithdrawAmount != 0 {
		n += 1 + sovWithdraw(uint64(m.WithdrawAmount))
	}
	l = len(m.TwilightAddress)
	if l > 0 {
		n += 1 + l + sovWithdraw(uint64(l))
	}
	if m.IsConfirmed {
		n += 2
	}
	if m.CreationTwilightBlockHeight != 0 {
		n += 1 + sovWithdraw(uint64(m.CreationTwilightBlockHeight))
	}
	return n
}

func (m *ReserveWithdrawPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReserveID != 0 {
		n += 1 + sovWithdraw(uint64(m.ReserveID))
	}
	if m.RoundID != 0 {
		n += 1 + sovWithdraw(uint64(m.RoundID))
	}
	if len(m.ProcessingWithdrawIdentifiers) > 0 {
		l = 0
		for _, e := range m.ProcessingWithdrawIdentifiers {
			l += sovWithdraw(uint64(e))
		}
		n += 1 + sovWithdraw(uint64(l)) + l
	}
	if len(m.QueuedWithdrawIdentifiers) > 0 {
		l = 0
		for _, e := range m.QueuedWithdrawIdentifiers {
			l += sovWithdraw(uint64(e))
		}
		n += 1 + sovWithdraw(uint64(l)) + l
	}
	if m.CurrentProcessingIndex != 0 {
		n += 1 + sovWithdraw(uint64(m.CurrentProcessingIndex))
	}
	return n
}

func (m *WithdrawRequestSnap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WithdrawIdentifier != 0 {
		n += 1 + sovWithdraw(uint64(m.WithdrawIdentifier))
	}
	l = len(m.WithdrawAddress)
	if l > 0 {
		n += 1 + l + sovWithdraw(uint64(l))
	}
	if m.WithdrawAmount != 0 {
		n += 1 + sovWithdraw(uint64(m.WithdrawAmount))
	}
	return n
}

func (m *LastReserveWithdrawSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReserveId != 0 {
		n += 1 + sovWithdraw(uint64(m.ReserveId))
	}
	if m.RoundId != 0 {
		n += 1 + sovWithdraw(uint64(m.RoundId))
	}
	if len(m.WithdrawRequests) > 0 {
		for _, e := range m.WithdrawRequests {
			l = e.Size()
			n += 1 + l + sovWithdraw(uint64(l))
		}
	}
	if m.EndBlockerHeightTwilight != 0 {
		n += 1 + sovWithdraw(uint64(m.EndBlockerHeightTwilight))
	}
	return n
}

func sovWithdraw(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWithdraw(x uint64) (n int) {
	return sovWithdraw(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BtcWithdrawRequestInternal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWithdraw
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BtcWithdrawRequestInternal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BtcWithdrawRequestInternal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawIdentifier", wireType)
			}
			m.WithdrawIdentifier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawIdentifier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdraw
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdraw
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawReserveId", wireType)
			}
			m.WithdrawReserveId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawReserveId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawAmount", wireType)
			}
			m.WithdrawAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdraw
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdraw
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsConfirmed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsConfirmed = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTwilightBlockHeight", wireType)
			}
			m.CreationTwilightBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationTwilightBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWithdraw(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWithdraw
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReserveWithdrawPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWithdraw
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReserveWithdrawPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReserveWithdrawPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveID", wireType)
			}
			m.ReserveID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundID", wireType)
			}
			m.RoundID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoundID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWithdraw
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ProcessingWithdrawIdentifiers = append(m.ProcessingWithdrawIdentifiers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWithdraw
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthWithdraw
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthWithdraw
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ProcessingWithdrawIdentifiers) == 0 {
					m.ProcessingWithdrawIdentifiers = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWithdraw
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ProcessingWithdrawIdentifiers = append(m.ProcessingWithdrawIdentifiers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessingWithdrawIdentifiers", wireType)
			}
		case 4:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWithdraw
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.QueuedWithdrawIdentifiers = append(m.QueuedWithdrawIdentifiers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWithdraw
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthWithdraw
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthWithdraw
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.QueuedWithdrawIdentifiers) == 0 {
					m.QueuedWithdrawIdentifiers = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWithdraw
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.QueuedWithdrawIdentifiers = append(m.QueuedWithdrawIdentifiers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field QueuedWithdrawIdentifiers", wireType)
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentProcessingIndex", wireType)
			}
			m.CurrentProcessingIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentProcessingIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWithdraw(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWithdraw
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WithdrawRequestSnap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWithdraw
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WithdrawRequestSnap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WithdrawRequestSnap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawIdentifier", wireType)
			}
			m.WithdrawIdentifier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawIdentifier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdraw
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdraw
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawAmount", wireType)
			}
			m.WithdrawAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWithdraw(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWithdraw
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LastReserveWithdrawSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWithdraw
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LastReserveWithdrawSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LastReserveWithdrawSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveId", wireType)
			}
			m.ReserveId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundId", wireType)
			}
			m.RoundId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoundId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawRequests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWithdraw
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWithdraw
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawRequests = append(m.WithdrawRequests, &WithdrawRequestSnap{})
			if err := m.WithdrawRequests[len(m.WithdrawRequests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlockerHeightTwilight", wireType)
			}
			m.EndBlockerHeightTwilight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlockerHeightTwilight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWithdraw(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWithdraw
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWithdraw(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWithdraw
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWithdraw
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWithdraw
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWithdraw
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWithdraw
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWithdraw        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWithdraw          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWithdraw = fmt.Errorf("proto: unexpected end of group")
)
