// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgSweepProposal } from "./types/nyks/bridge/tx";
import { MsgConfirmBtcDeposit } from "./types/nyks/bridge/tx";
import { MsgRegisterReserveAddress } from "./types/nyks/bridge/tx";
import { MsgRegisterBtcDepositAddress } from "./types/nyks/bridge/tx";
import { MsgRegisterJudge } from "./types/nyks/bridge/tx";
import { MsgWithdrawRequest } from "./types/nyks/bridge/tx";

import { EventRegisterBtcDepositAddress as typeEventRegisterBtcDepositAddress} from "./types"
import { EventRegisterReserveScript as typeEventRegisterReserveScript} from "./types"
import { EventRegisterJudgeAddress as typeEventRegisterJudgeAddress} from "./types"
import { Params as typeParams} from "./types"

export { MsgSweepProposal, MsgConfirmBtcDeposit, MsgRegisterReserveAddress, MsgRegisterBtcDepositAddress, MsgRegisterJudge, MsgWithdrawRequest };

type sendMsgSweepProposalParams = {
  value: MsgSweepProposal,
  fee?: StdFee,
  memo?: string
};

type sendMsgConfirmBtcDepositParams = {
  value: MsgConfirmBtcDeposit,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegisterReserveAddressParams = {
  value: MsgRegisterReserveAddress,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegisterBtcDepositAddressParams = {
  value: MsgRegisterBtcDepositAddress,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegisterJudgeParams = {
  value: MsgRegisterJudge,
  fee?: StdFee,
  memo?: string
};

type sendMsgWithdrawRequestParams = {
  value: MsgWithdrawRequest,
  fee?: StdFee,
  memo?: string
};


type msgSweepProposalParams = {
  value: MsgSweepProposal,
};

type msgConfirmBtcDepositParams = {
  value: MsgConfirmBtcDeposit,
};

type msgRegisterReserveAddressParams = {
  value: MsgRegisterReserveAddress,
};

type msgRegisterBtcDepositAddressParams = {
  value: MsgRegisterBtcDepositAddress,
};

type msgRegisterJudgeParams = {
  value: MsgRegisterJudge,
};

type msgWithdrawRequestParams = {
  value: MsgWithdrawRequest,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgSweepProposal({ value, fee, memo }: sendMsgSweepProposalParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSweepProposal: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSweepProposal({ value: MsgSweepProposal.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSweepProposal: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgConfirmBtcDeposit({ value, fee, memo }: sendMsgConfirmBtcDepositParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgConfirmBtcDeposit: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgConfirmBtcDeposit({ value: MsgConfirmBtcDeposit.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgConfirmBtcDeposit: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegisterReserveAddress({ value, fee, memo }: sendMsgRegisterReserveAddressParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterReserveAddress: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegisterReserveAddress({ value: MsgRegisterReserveAddress.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterReserveAddress: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegisterBtcDepositAddress({ value, fee, memo }: sendMsgRegisterBtcDepositAddressParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterBtcDepositAddress: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegisterBtcDepositAddress({ value: MsgRegisterBtcDepositAddress.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterBtcDepositAddress: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegisterJudge({ value, fee, memo }: sendMsgRegisterJudgeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterJudge: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegisterJudge({ value: MsgRegisterJudge.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterJudge: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgWithdrawRequest({ value, fee, memo }: sendMsgWithdrawRequestParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgWithdrawRequest: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgWithdrawRequest({ value: MsgWithdrawRequest.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgWithdrawRequest: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgSweepProposal({ value }: msgSweepProposalParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.bridge.MsgSweepProposal", value: MsgSweepProposal.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSweepProposal: Could not create message: ' + e.message)
			}
		},
		
		msgConfirmBtcDeposit({ value }: msgConfirmBtcDepositParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.bridge.MsgConfirmBtcDeposit", value: MsgConfirmBtcDeposit.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgConfirmBtcDeposit: Could not create message: ' + e.message)
			}
		},
		
		msgRegisterReserveAddress({ value }: msgRegisterReserveAddressParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.bridge.MsgRegisterReserveAddress", value: MsgRegisterReserveAddress.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterReserveAddress: Could not create message: ' + e.message)
			}
		},
		
		msgRegisterBtcDepositAddress({ value }: msgRegisterBtcDepositAddressParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.bridge.MsgRegisterBtcDepositAddress", value: MsgRegisterBtcDepositAddress.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterBtcDepositAddress: Could not create message: ' + e.message)
			}
		},
		
		msgRegisterJudge({ value }: msgRegisterJudgeParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.bridge.MsgRegisterJudge", value: MsgRegisterJudge.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterJudge: Could not create message: ' + e.message)
			}
		},
		
		msgWithdrawRequest({ value }: msgWithdrawRequestParams): EncodeObject {
			try {
				return { typeUrl: "/twilightproject.nyks.bridge.MsgWithdrawRequest", value: MsgWithdrawRequest.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgWithdrawRequest: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						EventRegisterBtcDepositAddress: getStructure(typeEventRegisterBtcDepositAddress.fromPartial({})),
						EventRegisterReserveScript: getStructure(typeEventRegisterReserveScript.fromPartial({})),
						EventRegisterJudgeAddress: getStructure(typeEventRegisterJudgeAddress.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			TwilightprojectNyksBridge: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;