// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nyks/fragment/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/twilight-project/nyks/x/volt/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSignerApplication struct {
	FragmentId     uint64 `protobuf:"varint,2,opt,name=fragmentId,proto3" json:"fragmentId,omitempty"`
	ApplicationFee uint64 `protobuf:"varint,3,opt,name=applicationFee,proto3" json:"applicationFee,omitempty"`
	BtcPubKey      string `protobuf:"bytes,4,opt,name=btcPubKey,proto3" json:"btcPubKey,omitempty"`
	SignerAddress  string `protobuf:"bytes,5,opt,name=signerAddress,proto3" json:"signerAddress,omitempty"`
}

func (m *MsgSignerApplication) Reset()         { *m = MsgSignerApplication{} }
func (m *MsgSignerApplication) String() string { return proto.CompactTextString(m) }
func (*MsgSignerApplication) ProtoMessage()    {}
func (*MsgSignerApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c3b1d039097173, []int{0}
}
func (m *MsgSignerApplication) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSignerApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSignerApplication.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSignerApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignerApplication.Merge(m, src)
}
func (m *MsgSignerApplication) XXX_Size() int {
	return m.Size()
}
func (m *MsgSignerApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignerApplication.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignerApplication proto.InternalMessageInfo

func (m *MsgSignerApplication) GetFragmentId() uint64 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *MsgSignerApplication) GetApplicationFee() uint64 {
	if m != nil {
		return m.ApplicationFee
	}
	return 0
}

func (m *MsgSignerApplication) GetBtcPubKey() string {
	if m != nil {
		return m.BtcPubKey
	}
	return ""
}

func (m *MsgSignerApplication) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

type MsgSignerApplicationResponse struct {
}

func (m *MsgSignerApplicationResponse) Reset()         { *m = MsgSignerApplicationResponse{} }
func (m *MsgSignerApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSignerApplicationResponse) ProtoMessage()    {}
func (*MsgSignerApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c3b1d039097173, []int{1}
}
func (m *MsgSignerApplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSignerApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSignerApplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSignerApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignerApplicationResponse.Merge(m, src)
}
func (m *MsgSignerApplicationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSignerApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignerApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignerApplicationResponse proto.InternalMessageInfo

type MsgAcceptSigners struct {
	FragmentId      int32  `protobuf:"varint,2,opt,name=fragmentId,proto3" json:"fragmentId,omitempty"`
	SignerAddresses string `protobuf:"bytes,3,opt,name=signerAddresses,proto3" json:"signerAddresses,omitempty"`
	JudgeAddress    string `protobuf:"bytes,4,opt,name=judgeAddress,proto3" json:"judgeAddress,omitempty"`
}

func (m *MsgAcceptSigners) Reset()         { *m = MsgAcceptSigners{} }
func (m *MsgAcceptSigners) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptSigners) ProtoMessage()    {}
func (*MsgAcceptSigners) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c3b1d039097173, []int{2}
}
func (m *MsgAcceptSigners) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptSigners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptSigners.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptSigners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptSigners.Merge(m, src)
}
func (m *MsgAcceptSigners) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptSigners) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptSigners.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptSigners proto.InternalMessageInfo

func (m *MsgAcceptSigners) GetFragmentId() int32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *MsgAcceptSigners) GetSignerAddresses() string {
	if m != nil {
		return m.SignerAddresses
	}
	return ""
}

func (m *MsgAcceptSigners) GetJudgeAddress() string {
	if m != nil {
		return m.JudgeAddress
	}
	return ""
}

type MsgAcceptSignersResponse struct {
}

func (m *MsgAcceptSignersResponse) Reset()         { *m = MsgAcceptSignersResponse{} }
func (m *MsgAcceptSignersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptSignersResponse) ProtoMessage()    {}
func (*MsgAcceptSignersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c3b1d039097173, []int{3}
}
func (m *MsgAcceptSignersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptSignersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptSignersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptSignersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptSignersResponse.Merge(m, src)
}
func (m *MsgAcceptSignersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptSignersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptSignersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptSignersResponse proto.InternalMessageInfo

type Fragment struct {
	FragmentID     string              `protobuf:"bytes,1,opt,name=FragmentID,proto3" json:"FragmentID,omitempty"`
	FragmentStatus bool                `protobuf:"varint,2,opt,name=FragmentStatus,proto3" json:"FragmentStatus,omitempty"`
	JudgeAddress   string              `protobuf:"bytes,3,opt,name=JudgeAddress,proto3" json:"JudgeAddress,omitempty"`
	JudgeStatus    string              `protobuf:"bytes,4,opt,name=JudgeStatus,proto3" json:"JudgeStatus,omitempty"`
	Signers        []*FragmentSigners  `protobuf:"bytes,5,rep,name=Signers,proto3" json:"Signers,omitempty"`
	FeePool        uint64              `protobuf:"varint,6,opt,name=FeePool,proto3" json:"FeePool,omitempty"`
	Reserves       []*types.BtcReserve `protobuf:"bytes,7,rep,name=Reserves,proto3" json:"Reserves,omitempty"`
}

func (m *Fragment) Reset()         { *m = Fragment{} }
func (m *Fragment) String() string { return proto.CompactTextString(m) }
func (*Fragment) ProtoMessage()    {}
func (*Fragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c3b1d039097173, []int{4}
}
func (m *Fragment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fragment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fragment.Merge(m, src)
}
func (m *Fragment) XXX_Size() int {
	return m.Size()
}
func (m *Fragment) XXX_DiscardUnknown() {
	xxx_messageInfo_Fragment.DiscardUnknown(m)
}

var xxx_messageInfo_Fragment proto.InternalMessageInfo

func (m *Fragment) GetFragmentID() string {
	if m != nil {
		return m.FragmentID
	}
	return ""
}

func (m *Fragment) GetFragmentStatus() bool {
	if m != nil {
		return m.FragmentStatus
	}
	return false
}

func (m *Fragment) GetJudgeAddress() string {
	if m != nil {
		return m.JudgeAddress
	}
	return ""
}

func (m *Fragment) GetJudgeStatus() string {
	if m != nil {
		return m.JudgeStatus
	}
	return ""
}

func (m *Fragment) GetSigners() []*FragmentSigners {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *Fragment) GetFeePool() uint64 {
	if m != nil {
		return m.FeePool
	}
	return 0
}

func (m *Fragment) GetReserves() []*types.BtcReserve {
	if m != nil {
		return m.Reserves
	}
	return nil
}

type FragmentSigners struct {
	FragmentID           string `protobuf:"bytes,1,opt,name=fragmentID,proto3" json:"fragmentID,omitempty"`
	SignerAddress        string `protobuf:"bytes,2,opt,name=signerAddress,proto3" json:"signerAddress,omitempty"`
	SignerStatus         string `protobuf:"bytes,3,opt,name=signerStatus,proto3" json:"signerStatus,omitempty"`
	SignerBTCPublicKey   string `protobuf:"bytes,4,opt,name=signerBTCPublicKey,proto3" json:"signerBTCPublicKey,omitempty"`
	SignerApplicationFee uint32 `protobuf:"varint,5,opt,name=signerApplicationFee,proto3" json:"signerApplicationFee,omitempty"`
}

func (m *FragmentSigners) Reset()         { *m = FragmentSigners{} }
func (m *FragmentSigners) String() string { return proto.CompactTextString(m) }
func (*FragmentSigners) ProtoMessage()    {}
func (*FragmentSigners) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c3b1d039097173, []int{5}
}
func (m *FragmentSigners) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FragmentSigners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FragmentSigners.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FragmentSigners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentSigners.Merge(m, src)
}
func (m *FragmentSigners) XXX_Size() int {
	return m.Size()
}
func (m *FragmentSigners) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentSigners.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentSigners proto.InternalMessageInfo

func (m *FragmentSigners) GetFragmentID() string {
	if m != nil {
		return m.FragmentID
	}
	return ""
}

func (m *FragmentSigners) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *FragmentSigners) GetSignerStatus() string {
	if m != nil {
		return m.SignerStatus
	}
	return ""
}

func (m *FragmentSigners) GetSignerBTCPublicKey() string {
	if m != nil {
		return m.SignerBTCPublicKey
	}
	return ""
}

func (m *FragmentSigners) GetSignerApplicationFee() uint32 {
	if m != nil {
		return m.SignerApplicationFee
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSignerApplication)(nil), "twilightproject.nyks.fragment.MsgSignerApplication")
	proto.RegisterType((*MsgSignerApplicationResponse)(nil), "twilightproject.nyks.fragment.MsgSignerApplicationResponse")
	proto.RegisterType((*MsgAcceptSigners)(nil), "twilightproject.nyks.fragment.MsgAcceptSigners")
	proto.RegisterType((*MsgAcceptSignersResponse)(nil), "twilightproject.nyks.fragment.MsgAcceptSignersResponse")
	proto.RegisterType((*Fragment)(nil), "twilightproject.nyks.fragment.Fragment")
	proto.RegisterType((*FragmentSigners)(nil), "twilightproject.nyks.fragment.fragmentSigners")
}

func init() { proto.RegisterFile("nyks/fragment/tx.proto", fileDescriptor_e0c3b1d039097173) }

var fileDescriptor_e0c3b1d039097173 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xcd, 0x26, 0x4d, 0x93, 0x4c, 0xbf, 0x7c, 0x85, 0x55, 0x05, 0xab, 0xa8, 0x58, 0x91, 0x05,
	0x28, 0x17, 0x6c, 0x91, 0x1e, 0x38, 0x70, 0x4a, 0x40, 0x11, 0xa5, 0x8a, 0x14, 0xb9, 0x9c, 0xb8,
	0xc5, 0xce, 0xe2, 0xba, 0xb8, 0xb6, 0xe5, 0x5d, 0x97, 0xe6, 0xc6, 0x05, 0x89, 0x23, 0xbf, 0x81,
	0x3f, 0xc2, 0x95, 0x63, 0x8f, 0xdc, 0x40, 0xc9, 0x1f, 0x41, 0xde, 0xf5, 0x26, 0xb6, 0x6b, 0x51,
	0xc1, 0xcd, 0xfb, 0x3c, 0x6f, 0xe6, 0xcd, 0xec, 0x9b, 0x85, 0x7b, 0xc1, 0xf2, 0x3d, 0x33, 0xdf,
	0xc5, 0x73, 0xf7, 0x82, 0x06, 0xdc, 0xe4, 0x57, 0x46, 0x14, 0x87, 0x3c, 0xc4, 0x0f, 0xf8, 0x07,
	0xcf, 0xf7, 0xdc, 0x33, 0x1e, 0xc5, 0xe1, 0x39, 0x75, 0xb8, 0x91, 0xc6, 0x19, 0x2a, 0xae, 0x77,
	0x5f, 0xd0, 0x2e, 0x43, 0x9f, 0x9b, 0x31, 0x65, 0x34, 0xbe, 0xa4, 0x92, 0xa7, 0x7f, 0x45, 0x70,
	0x30, 0x65, 0xee, 0xa9, 0xe7, 0x06, 0x34, 0x1e, 0x45, 0x91, 0xef, 0x39, 0x73, 0xee, 0x85, 0x01,
	0xd6, 0x00, 0x14, 0xfb, 0x78, 0x41, 0xea, 0x7d, 0x34, 0xd8, 0xb1, 0x72, 0x08, 0x7e, 0x0c, 0xff,
	0xcf, 0xb7, 0xe1, 0x13, 0x4a, 0x49, 0x43, 0xc4, 0x94, 0x50, 0x7c, 0x08, 0x1d, 0x9b, 0x3b, 0xb3,
	0xc4, 0x3e, 0xa1, 0x4b, 0xb2, 0xd3, 0x47, 0x83, 0x8e, 0xb5, 0x05, 0xf0, 0x43, 0xe8, 0x32, 0x59,
	0x7a, 0xb1, 0x88, 0x29, 0x63, 0xa4, 0x29, 0x22, 0x8a, 0xa0, 0xae, 0xc1, 0x61, 0x95, 0x46, 0x8b,
	0xb2, 0x28, 0x0c, 0x18, 0xd5, 0x3f, 0x22, 0xb8, 0x33, 0x65, 0xee, 0xc8, 0x71, 0x68, 0xc4, 0x65,
	0x18, 0xab, 0x68, 0xa0, 0x59, 0x68, 0x60, 0x00, 0xfb, 0x85, 0x2a, 0x94, 0x89, 0x0e, 0x3a, 0x56,
	0x19, 0xc6, 0x3a, 0xfc, 0x77, 0x9e, 0x2c, 0x5c, 0xaa, 0x34, 0xca, 0x2e, 0x0a, 0x98, 0xde, 0x03,
	0x52, 0x56, 0xb0, 0x91, 0xf7, 0xad, 0x0e, 0xed, 0x49, 0x56, 0x38, 0x95, 0xa5, 0xbe, 0x8f, 0x5f,
	0x12, 0x24, 0x52, 0xe5, 0x90, 0x74, 0xae, 0xea, 0x74, 0xca, 0xe7, 0x3c, 0x61, 0x42, 0x7a, 0xdb,
	0x2a, 0xa1, 0xa9, 0xa8, 0xd7, 0x79, 0x51, 0x52, 0x7b, 0x01, 0xc3, 0x7d, 0xd8, 0x13, 0xe7, 0x2c,
	0x91, 0xd4, 0x9d, 0x87, 0xf0, 0x2b, 0x68, 0x65, 0x6a, 0x49, 0xb3, 0xdf, 0x18, 0xec, 0x0d, 0x0d,
	0xe3, 0x8f, 0x46, 0xda, 0x7c, 0xa8, 0x1e, 0x15, 0x1d, 0x13, 0x68, 0x4d, 0x28, 0x9d, 0x85, 0xa1,
	0x4f, 0x76, 0x85, 0x11, 0xd4, 0x11, 0x8f, 0xa0, 0x6d, 0x49, 0xcf, 0x31, 0xd2, 0x12, 0x45, 0x1e,
	0x55, 0x17, 0x49, 0xed, 0x69, 0x8c, 0xb9, 0x93, 0x45, 0x5b, 0x1b, 0x9a, 0xfe, 0x13, 0xc1, 0x7e,
	0xa9, 0x72, 0xe1, 0x7e, 0x37, 0x83, 0xdc, 0x22, 0x37, 0xad, 0x55, 0xaf, 0xb0, 0x56, 0x3a, 0x46,
	0x09, 0x64, 0x33, 0xca, 0xc6, 0x98, 0xc7, 0xb0, 0x01, 0x58, 0x9e, 0xc7, 0x6f, 0x5e, 0xcc, 0x12,
	0xdb, 0xf7, 0x9c, 0xad, 0x97, 0x2b, 0xfe, 0xe0, 0x21, 0x1c, 0xb0, 0xb2, 0x57, 0xd3, 0x05, 0x49,
	0xbd, 0xdd, 0xb5, 0x2a, 0xff, 0x0d, 0x3f, 0xd7, 0xa1, 0x31, 0x65, 0x2e, 0xfe, 0x84, 0xe0, 0xee,
	0xcd, 0x65, 0x3c, 0xba, 0xe5, 0x56, 0xaa, 0xb6, 0xa3, 0xf7, 0xfc, 0x1f, 0x48, 0xca, 0xb3, 0x78,
	0x09, 0xdd, 0xe2, 0x3a, 0x99, 0xb7, 0x67, 0x2b, 0x10, 0x7a, 0xcf, 0xfe, 0x92, 0xa0, 0x4a, 0x8f,
	0x4f, 0xbe, 0xaf, 0x34, 0x74, 0xbd, 0xd2, 0xd0, 0xaf, 0x95, 0x86, 0xbe, 0xac, 0xb5, 0xda, 0xf5,
	0x5a, 0xab, 0xfd, 0x58, 0x6b, 0xb5, 0xb7, 0x4f, 0x5d, 0x8f, 0x9f, 0x25, 0xb6, 0xe1, 0x84, 0x17,
	0xa6, 0x4a, 0xfe, 0x24, 0xcb, 0x6e, 0x8a, 0x17, 0xee, 0x2a, 0xf7, 0x34, 0x2e, 0x23, 0xca, 0xec,
	0x5d, 0xf1, 0xcc, 0x1d, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xac, 0xdd, 0xe7, 0x0c, 0x38, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SignerApplication(ctx context.Context, in *MsgSignerApplication, opts ...grpc.CallOption) (*MsgSignerApplicationResponse, error)
	AcceptSigners(ctx context.Context, in *MsgAcceptSigners, opts ...grpc.CallOption) (*MsgAcceptSignersResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SignerApplication(ctx context.Context, in *MsgSignerApplication, opts ...grpc.CallOption) (*MsgSignerApplicationResponse, error) {
	out := new(MsgSignerApplicationResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.fragment.Msg/SignerApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AcceptSigners(ctx context.Context, in *MsgAcceptSigners, opts ...grpc.CallOption) (*MsgAcceptSignersResponse, error) {
	out := new(MsgAcceptSignersResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.fragment.Msg/AcceptSigners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SignerApplication(context.Context, *MsgSignerApplication) (*MsgSignerApplicationResponse, error)
	AcceptSigners(context.Context, *MsgAcceptSigners) (*MsgAcceptSignersResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SignerApplication(ctx context.Context, req *MsgSignerApplication) (*MsgSignerApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignerApplication not implemented")
}
func (*UnimplementedMsgServer) AcceptSigners(ctx context.Context, req *MsgAcceptSigners) (*MsgAcceptSignersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptSigners not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SignerApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSignerApplication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SignerApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.fragment.Msg/SignerApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SignerApplication(ctx, req.(*MsgSignerApplication))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AcceptSigners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAcceptSigners)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AcceptSigners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.fragment.Msg/AcceptSigners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AcceptSigners(ctx, req.(*MsgAcceptSigners))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.fragment.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignerApplication",
			Handler:    _Msg_SignerApplication_Handler,
		},
		{
			MethodName: "AcceptSigners",
			Handler:    _Msg_AcceptSigners_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nyks/fragment/tx.proto",
}

func (m *MsgSignerApplication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSignerApplication) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSignerApplication) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignerAddress) > 0 {
		i -= len(m.SignerAddress)
		copy(dAtA[i:], m.SignerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BtcPubKey) > 0 {
		i -= len(m.BtcPubKey)
		copy(dAtA[i:], m.BtcPubKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcPubKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.ApplicationFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ApplicationFee))
		i--
		dAtA[i] = 0x18
	}
	if m.FragmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentId))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *MsgSignerApplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSignerApplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSignerApplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAcceptSigners) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptSigners) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptSigners) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JudgeAddress) > 0 {
		i -= len(m.JudgeAddress)
		copy(dAtA[i:], m.JudgeAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JudgeAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SignerAddresses) > 0 {
		i -= len(m.SignerAddresses)
		copy(dAtA[i:], m.SignerAddresses)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddresses)))
		i--
		dAtA[i] = 0x1a
	}
	if m.FragmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentId))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptSignersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptSignersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptSignersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Fragment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fragment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fragment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reserves) > 0 {
		for iNdEx := len(m.Reserves) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reserves[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.FeePool != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FeePool))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Signers) > 0 {
		for iNdEx := len(m.Signers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.JudgeStatus) > 0 {
		i -= len(m.JudgeStatus)
		copy(dAtA[i:], m.JudgeStatus)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JudgeStatus)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.JudgeAddress) > 0 {
		i -= len(m.JudgeAddress)
		copy(dAtA[i:], m.JudgeAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JudgeAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.FragmentStatus {
		i--
		if m.FragmentStatus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.FragmentID) > 0 {
		i -= len(m.FragmentID)
		copy(dAtA[i:], m.FragmentID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FragmentID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FragmentSigners) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FragmentSigners) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FragmentSigners) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignerApplicationFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignerApplicationFee))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SignerBTCPublicKey) > 0 {
		i -= len(m.SignerBTCPublicKey)
		copy(dAtA[i:], m.SignerBTCPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerBTCPublicKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SignerStatus) > 0 {
		i -= len(m.SignerStatus)
		copy(dAtA[i:], m.SignerStatus)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerStatus)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SignerAddress) > 0 {
		i -= len(m.SignerAddress)
		copy(dAtA[i:], m.SignerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.FragmentID) > 0 {
		i -= len(m.FragmentID)
		copy(dAtA[i:], m.FragmentID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FragmentID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSignerApplication) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FragmentId != 0 {
		n += 1 + sovTx(uint64(m.FragmentId))
	}
	if m.ApplicationFee != 0 {
		n += 1 + sovTx(uint64(m.ApplicationFee))
	}
	l = len(m.BtcPubKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSignerApplicationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAcceptSigners) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FragmentId != 0 {
		n += 1 + sovTx(uint64(m.FragmentId))
	}
	l = len(m.SignerAddresses)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.JudgeAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAcceptSignersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Fragment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FragmentID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.FragmentStatus {
		n += 2
	}
	l = len(m.JudgeAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.JudgeStatus)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Signers) > 0 {
		for _, e := range m.Signers {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.FeePool != 0 {
		n += 1 + sovTx(uint64(m.FeePool))
	}
	if len(m.Reserves) > 0 {
		for _, e := range m.Reserves {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *FragmentSigners) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FragmentID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerStatus)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerBTCPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SignerApplicationFee != 0 {
		n += 1 + sovTx(uint64(m.SignerApplicationFee))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSignerApplication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignerApplication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignerApplication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentId", wireType)
			}
			m.FragmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationFee", wireType)
			}
			m.ApplicationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSignerApplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignerApplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignerApplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptSigners) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptSigners: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptSigners: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentId", wireType)
			}
			m.FragmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddresses = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JudgeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptSignersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptSignersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptSignersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fragment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fragment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fragment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FragmentID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentStatus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FragmentStatus = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JudgeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JudgeStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signers = append(m.Signers, &FragmentSigners{})
			if err := m.Signers[len(m.Signers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePool", wireType)
			}
			m.FeePool = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeePool |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserves", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserves = append(m.Reserves, &types.BtcReserve{})
			if err := m.Reserves[len(m.Reserves)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FragmentSigners) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: fragmentSigners: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: fragmentSigners: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FragmentID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerBTCPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerBTCPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerApplicationFee", wireType)
			}
			m.SignerApplicationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerApplicationFee |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
